### ISSUE TITLE
arp-scan does not look in /usr/share/arp-scan if trying to open ieee-oui.txt failes with EACCESS

### ISSUE THREAD

**Issue by jaskij** [royhills/arp-scan#119] opened 2023-01-12 12:51 UTC
As the title says, when running arp-scan (1.10.0, current Arch package), I am getting this `strace`:

```strace
newfstatat(AT_FDCWD, "ieee-oui.txt", 0x7ffd97bee920, 0) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "ieee-oui.txt", O_RDONLY) = -1 EACCES (Permission denied)
WARNING: Cannot open MAC/Vendor file ieee-oui.txt: Permission denied
newfstatat(AT_FDCWD, "mac-vendor.txt", 0x7ffd97bee920, 0) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "mac-vendor.txt", O_RDONLY) = -1 EACCES (Permission denied)
WARNING: Cannot open MAC/Vendor file mac-vendor.txt: Permission denied
```

What's weird is that the file actually exists, and has proper permissions:

```
#  ll /usr/share/arp-scan/ieee-oui.txt
-rw-r--r-- 1 root root 1,4M 12-19 15:39 /usr/share/arp-scan/ieee-oui.txt
```

And, if I enter the directory `/usr/share/arp-scan`, and run `arp-scan` from there, it loads the database properly and works as intended.

**Comment by royhills** [comment] 2023-01-13 16:34
Are you running `arp-scan` as root with `sudo`? That can cause file permission issues if it is capabilities aware. I suspect that may be what is happening here.

Here is the text from the `arp-scan` `NEWS.md` file (not included in the arch package but available on github):

```
* **POSIX.1e capabilities support for Linux systems with libcap.**

  - Uses `CAP_NET_RAW` capability instead of superuser (root) permissions.
  - May need `libcap-dev` or similar package to build. *Note that `libcap`
    (capabilities) and `libpcap` (packet capture) are different libraries.*
  - configure option `--with-libcap`, defaults to auto.
  - Can set capability on exe with: `setcap cap_net_raw+p /path/to/arp-scan`
  - Initially clears effective set completely and clears everything except
    CAP_NET_RAW from the permitted set. Only enables CAP_NET_RAW in effective
    set for the functions that open raw sockets. Once sockets opened, removes
    CAP_NET_RAW from both effective and permitted set so process can never
    re enable it.
  - If arp-scan is SUID root, will drop all capabilities except CAP_NET_RAW
    as above and will also drop SUID with `setuid(getuid())`. So SUID root is
    essentially as secure as `setcap cap_net_raw+p /path/to/arp-scan` and is a
    safe alternative if the filesystem does not support extended attributes.
  - If arp-scan is run as root, e.g. `sudo`, it will drop all capabilities
    except CAP_NET_RAW and proceed as previously, but will remain as UID 0
    and may encounter file permissions issues if it tries to open files with
    e.g. `--pcapsavefile` or `--ouifile` in user directories.
  - `--version` displays `Built with libcap POSIX.1e capability support` if
    enabled.
  - `make install` installs the arp-scan executable with the `CAP_NET_RAW`
    capability if `setcap` is available and works. Otherwise will fallback to
    SUID. See `install-exec-hook` in `Makefile.am` for details.
```

The arp-scan arch package is built with POSIX.1e capabilities support:
```
[rsh@arch ~]$ arp-scan --version
arp-scan 1.10.0

Copyright (C) 2005-2022 Roy Hills
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

libpcap version 1.10.2 (with TPACKET_V3)
Built with libcap POSIX.1e capability support.
```

The package installs the `arp-scan` executable with `CAP_NET_RAW` capability in the permitted set:
```
[root@arch ~]# getcap /usr/bin/arp-scan
/usr/bin/arp-scan cap_net_raw=p
```

`arp-scan` runs without needing root permissions because it is capabilities aware and has been installed with the *CAP_NET_RAW* capability:
```
[rsh@arch ~]$ arp-scan --localnet
Interface: ens33, type: EN10MB, MAC: 00:0c:29:56:64:20, IPv4: 192.168.14.150
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.14.2    00:50:56:e4:9a:83       VMware, Inc.
192.168.14.1    00:50:56:c0:00:08       VMware, Inc.
192.168.14.128  00:0c:29:d3:97:e8       VMware, Inc.
192.168.14.254  00:50:56:ea:b6:a8       VMware, Inc.

6 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 2.081 seconds (123.02 hosts/sec). 4 responded
```

If you are running `arp-scan` with `sudo` then I think the solution is that you don't need to use sudo because `arp-scan` is now capabilities aware and only needs the `CAP_NET_RAW` capability to open raw network sockets.

**Comment by royhills** [comment] 2023-01-13 18:10
Note that `arp-scan` will look for `ieee-oui` and `mac-vendor.txt` in the current directory before looking in the system locations (I think the manpage talks about this somewhere). So if it finds a file called `ieee-oui.txt` or `mac-vendor.txt` in the current directory it will try to open them. Running `sudo arp-scan ...` can cause `EACCES` failures if the completely unprivileged UID 0 process (not even with `CAP_NET_RAW` at this point) cannot open it.

I have observed this behaviour on my own system so I suspect it's what you are seeing. See ticket https://github.com/royhills/arp-scan/issues/21 and search for `Permission Denied`.

**Comment by jaskij** [comment] 2023-01-13 19:28
> If you are running arp-scan with sudo then I think the solution is that you don't need to use sudo because arp-scan is now capabilities aware and only needs the CAP_NET_RAW capability to open raw network sockets.

Yes, this works flawlessly.

I think I also found what is causing the issue - this happens only in my home directory, and not elsewhere. After checking, my home is set to `0700`, while other directories are usually set to `0755`. Some further testing shows that this happens whenever the user running `arp-scan` doesn't have the execute permission on current directory.

My initial thought when creating this issue was for a graceful fallback - since the error only produces a warning and the scan proceeds anyway, it would be nice to try opening the file in `/usr/share` if the one in current directory fails. Specifically, `newfstatat(AT_FDCWD, "ieee-oui.txt",...)` returning `EACCES` seems like a good candidate.

**Comment by royhills** [comment] 2023-01-13 21:15
The initial code change is in PR https://github.com/royhills/arp-scan/pull/120

I think that does what's needed, but I've still got to test it, update docs etc.

Thanks for reporting this regression.

**Comment by royhills** [comment] 2023-01-14 15:23
Changes merged into master branch.

**Comment by jaskij** [comment] 2023-01-14 15:25
Thank you for the prompt fix! Is building `arp-scan` involved? Otherwise I could test on my system.

**Comment by royhills** [comment] 2023-01-14 15:38
The changes have been made to the source code on github so you'll need to build arp-scan from the latest source to see the changes. The arch package won't get updated until the maintainer re-builds the binary package based on the latest source.

**Comment by jaskij** [comment] 2023-01-14 15:47
Ah, no, I was asking if building it from source is involved (some projects have such build processes). I will still wait for package update for the system arp-scan, but wanted to check if the fix works, and it does.

After building from source (with `./configure --with-pcap=yes --prefix=/usr`) and changing permissions to 0700, I got this `strace`, which seems to indicate this worked:

```
$ sudo strace -Z ./arp-scan -lI br0
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffc29a78c70) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
prctl(PR_CAPBSET_READ, 0x30 /* CAP_??? */) = -1 EINVAL (Invalid argument)
prctl(PR_CAPBSET_READ, 0x2c /* CAP_??? */) = -1 EINVAL (Invalid argument)
prctl(PR_CAPBSET_READ, 0x2a /* CAP_??? */) = -1 EINVAL (Invalid argument)
prctl(PR_CAPBSET_READ, 0x29 /* CAP_??? */) = -1 EINVAL (Invalid argument)
ioctl(3, SIOCGIFNAME, {ifr_ifindex=0})  = -1 ENODEV (No such device)
newfstatat(AT_FDCWD, "/sys/class/net/br0/wireless", 0x7ffc29a78760, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sys/class/net/br0/dsa/tagging", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(5, SIOCGIFNAME, {ifr_ifindex=0})  = -1 ENODEV (No such device)
newfstatat(AT_FDCWD, "/sys/class/net/br0/wireless", 0x7ffc29a78690, 0) = -1 ENOENT (No such file or directory)
ioctl(5, SIOCGIFNAME, {ifr_ifindex=0})  = -1 ENODEV (No such device)
newfstatat(AT_FDCWD, "/sys/class/net/enp42s0/wireless", 0x7ffc29a78690, 0) = -1 ENOENT (No such file or directory)
ioctl(5, SIOCGIFNAME, {ifr_ifindex=0})  = -1 ENODEV (No such device)
ioctl(5, SIOCGIFNAME, {ifr_ifindex=0})  = -1 ENODEV (No such device)
newfstatat(AT_FDCWD, "/sys/class/net/veth7946f633/wireless", 0x7ffc29a78690, 0) = -1 ENOENT (No such file or directory)
ioctl(5, SIOCGIFNAME, {ifr_ifindex=0})  = -1 ENODEV (No such device)
newfstatat(AT_FDCWD, "/sys/class/net/tun0/wireless", 0x7ffc29a78690, 0) = -1 ENOENT (No such file or directory)
Interface: br0, type: EN10MB, MAC: b2:2c:77:19:c3:f8, IPv4: 192.168.0.10
recvfrom(4, 0x7ffc29a78977, 1, MSG_TRUNC, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
newfstatat(AT_FDCWD, "ieee-oui.txt", 0x7ffc29a78900, 0) = -1 EACCES (Permission denied)
newfstatat(AT_FDCWD, "mac-vendor.txt", 0x7ffc29a78900, 0) = -1 EACCES (Permission denied)
Starting arp-scan 1.10.1 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.0.1	e4:57:40:e3:4e:7a	ARRIS Group, Inc.
192.168.0.12	00:16:3e:8a:95:97	Xensource, Inc.
192.168.0.126	a2:71:85:ad:41:3a	(Unknown: locally administered)

3 packets received by filter, 0 packets dropped by kernel
setsockopt(4, SOL_PACKET, PACKET_RX_RING, {tp_block_size=0, tp_block_nr=0, tp_frame_size=0, tp_frame_nr=0}, 16) = -1 EBUSY (Device or resource busy)
Ending arp-scan 1.10.1: 256 hosts scanned in 2.115 seconds (121.04 hosts/sec). 3 responded
+++ exited with 0 +++
```

**Comment by royhills** [comment] 2023-01-14 17:35
Yes, that's behaving how I would expect: the `newfstatat` call is failing with `EACCES`, but arp-scan should then open the system version.  Your strace doesn't show the open because you're only showing failing calls.  If you use `strace -e newfstatat,openat,close` you should see something like this (in my case I'm installing under `/usr/local`):

```
newfstatat(AT_FDCWD, "ieee-oui.txt", 0x7ffe2ce57b80, 0) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/usr/local/share/arp-scan/ieee-oui.txt", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1455656, ...}, AT_EMPTY_PATH) = 0
close(3)                                = 0
newfstatat(AT_FDCWD, "mac-vendor.txt", 0x7ffe2ce57b80, 0) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/usr/local/etc/arp-scan/mac-vendor.txt", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2228, ...}, AT_EMPTY_PATH) = 0
close(3)                                = 0
```

By the way, most distros add `--sysconfdir=/etc` to `./configure` so `mac-vendor.txt` goes in `/etc/arp-scan` rather than `/usr/etc/arp-scan`, but the arch package doesn't do this. I'm not sure if that's intentional or not - `/usr/etc` is an unusual directory.

I think the issue is fixed for the most part now. I guess it's possible that someone might want to use a custom `ieee-oui.txt` file in the current directory and wonder why it's getting silently ignored when they use sudo. But I think that's unlikely.

**Comment by jaskij** [comment] 2023-01-14 17:39
All's well then, I believe. Nothing to add from me, close?

**Comment by royhills** [comment] 2023-01-14 17:41
Closed as fixed.  Thanks for raising this ticket.

**Closed by royhills** 2023-01-14 17:41 UTC
Labels: regression

**Comment by royhills** [comment] 2023-01-14 20:10
Related ticket opened on arch linux bug tracker: "*[arp-scan] 1.10.0-1 installs mac-vendor.txt in /usr/etc/arp-scan when it should be /etc/arp-scan*" https://bugs.archlinux.org/task/77127

**Comment by royhills** [comment] 2023-01-18 10:45
The arch packaging bug detailed in https://bugs.archlinux.org/task/77127 has been fixed by the package maintainer.

In package version `1.10.0-1`:

```
[rsh@arch ~]$ pacman -Ql arp-scan | grep mac-vendor.txt
arp-scan /usr/etc/arp-scan/mac-vendor.txt
```

In `1.10.0-2`:

```
[rsh@arch ~]$ pacman -Ql arp-scan | grep mac-vendor.txt
arp-scan /etc/arp-scan/mac-vendor.txt
```
