### ISSUE TITLE
add a option to force the reverse DNS lookups to convert the IP address to its hostname

### ISSUE THREAD

**Issue by MaxPeal** [royhills/arp-scan#71] opened 2022-02-09 13:13 UTC
as a user i really like to have a option to force the reverse DNS lookup to convert the IP address to its hostname,
so with a
arp-scan -l
it also print the Hostnames

reason for the request is with a lot of IoT devices its a pain to find the right one.

**Comment by royhills** [comment] 2022-10-07 21:13
Thanks for the suggestion - it's an obvious feature now you mention it.

Support added in commit f67abf9421482cfa5ea0d2cfb0020a0ac6309b28

--resolve option or -d

uses getnameinfo() to do the address to name translation, which uses the system resolver.  Will display the hostname if a reverse lookup exists otherwise the IP address.

Not fully tested though, so don't close just yet.

**Comment by royhills** [comment] 2022-10-11 16:34
Confirmed working after testing.  The only comment I have is that the output format can look a bit ragged when you have different length hostnames. This will probably require more flexibility in the output format, which will be handled in a seperate ticket.

**Comment by royhills** [comment] 2022-10-25 15:56
The ragged output with variable length hostnames will be addressed by the output formatting flexibility changes that are being worked on in issue https://github.com/royhills/arp-scan/issues/57. Please see that issue for details.

For this issue, the latest version on the *output-fields* branch allows a field width to be specified in the *--format* option.  Here is what this looks like with a right-justified 20 character field width for the "name" field and no field widths for "mac" and "vendor" with tab character as separator.

```
rsh@bullseye:~/arp-scan$ sudo ./arp-scan --localnet --resolve --format='${name;20}\t${mac}\t${vendor}'
Interface: ens33, type: EN10MB, MAC: 00:0c:29:d3:97:e8, IPv4: 192.168.14.128
Starting arp-scan 1.9.9 with 256 hosts (https://github.com/royhills/arp-scan)
     test2.home.arpa    00:50:56:e4:9a:83       VMware, Inc.
      test.home.arpa    00:50:56:c0:00:08       VMware, Inc.
      192.168.14.254    00:50:56:fc:ca:ea       VMware, Inc.

5 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.9: 256 hosts scanned in 1.911 seconds (133.96 hosts/sec). 3 responded
```

**Closed** 2022-10-26 18:23 UTC
Labels: enhancement

**Comment by mailinglists35** [comment] 2022-12-15 21:32
@royhills is there any chance you could add a new option to display both the ip and the reverse resolved name?

thanks!

**Comment by royhills** [comment] 2022-12-15 21:45
@mailinglists35: You could do this with, e.g.

```
rsh@bookworm:~$ arp-scan --resolve --format='${ip}\t${name}\t${vendor}' --localnet
Interface: ens33, type: EN10MB, MAC: 00:0c:29:d3:97:e8, IPv4: 192.168.14.128
Starting arp-scan 1.10-rc1 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.14.2    test2.home.arpa VMware, Inc.
192.168.14.1    test.home.arpa  VMware, Inc.
192.168.14.254  192.168.14.254  VMware, Inc.

5 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10-rc1: 256 hosts scanned in 1.913 seconds (133.82 hosts/sec). 3 responded
```

You need arp-scan version 1.10.0 for the `--format` option. The `${ip}` field is always available, and the `${name}` field is available if the `--resolve` option is given.

**Comment by mailinglists35** [comment] 2022-12-15 21:50
thank you!
I'm still getting misaligned columns, though. will shortly anonymize and post an example

**Comment by mailinglists35** [comment] 2022-12-15 21:57
ohwell, nevermind, I am doing it this way and it works

`sudo arp-scan --resolve --format='${ip};${name};${mac};${vendor}' --localnet --plain | column -t --separator \;`

let me know if you still want a sample output but for me this is no longer an issue since combining `--format` and piping to `column(1)`

**Comment by royhills** [comment] 2022-12-16 09:29
You can use `--format` field widths to align columns with `${field;width}`. Positive widths give right-alignment:

```
$ arp-scan --resolve --format='${ip;15};${name;20};${mac};${vendor}' --localnet --plain
   192.168.14.2;     test2.home.arpa;00:50:56:e4:9a:83;VMware, Inc.
   192.168.14.1;      test.home.arpa;00:50:56:c0:00:08;VMware, Inc.
 192.168.14.254;      192.168.14.254;00:50:56:ee:72:8a;VMware, Inc.
```

Negative widths give left-alignment:

```
$ arp-scan --resolve --format='${ip;-15};${name;-20};${mac};${vendor}' --localnet --plain
192.168.14.2   ;test2.home.arpa     ;00:50:56:e4:9a:83;VMware, Inc.
192.168.14.1   ;test.home.arpa      ;00:50:56:c0:00:08;VMware, Inc.
192.168.14.254 ;192.168.14.254      ;00:50:56:ee:72:8a;VMware, Inc.
```

It should be possible to use field widths to align the output in any way you like, but please let me know if it's not working for you or if it can be improved in some way.
