### ISSUE TITLE
scanning interface aliases not working anymore

### ISSUE THREAD

**Issue by Silex** [royhills/arp-scan#3] opened 2015-02-12 12:01 UTC
Hello,

Commit https://github.com/royhills/arp-scan/commit/5fc969d257a0b4918c3f1d31d91f6f1db92d0a6b introduced a regression:

``` shell
arp-scan -l -I eth0:0
ERROR: Could not find interface: eth0:0
ERROR: Check that the interface exists and is up
```

There's a pretty simple workaround by using `-s`:

``` shell
arp-scan -l -s 10.10.10.160 -I eth0:0
Interface: eth0:0, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9 with 256 hosts (http://www.nta-monitor.com/tools/arp-scan/)
10.10.10.1  00:30:18:a8:bd:c1   Jetway Information Co., Ltd.
10.10.10.16 00:15:17:64:23:fc   Intel Corporate
10.10.10.18 ee:69:48:f9:ba:14   (Unknown)
....
```

But I think the old behavior was better.

**Comment by Silex** [comment] 2015-02-19 14:19
@royhills: ping?

**Comment by royhills** [comment] 2015-02-20 12:41
This error comes from the get_source_ip() function, and appears to be a regression caused by the change made ion 25/04/2013 which changed this function from platform-specific code to playform-independent code.

The old platform specific code to get the interface IP address used differing methods depending on whether the platform was Linux, BSD or Solaris.  The new platform-independent code uses the libpcap function pcap_findalldevs().

I'll investigate why an apparently valid device name like the sub-interface shown on the example is not being recognised by this function.

**Comment by royhills** [comment] 2015-02-20 13:25
Looks like pcap_findalldevs() doesn't include sub-interfaces:

root@debian-wheezy:/home/rsh/arp-scan# ifconfig eth0:0
eth0:0    Link encap:Ethernet  HWaddr 00:0c:29:60:16:ec
          inet addr:10.0.0.1  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Interrupt:19 Base address:0x2000

root@debian-wheezy:/home/rsh/arp-scan# gdb ./arp-scan
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i486-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/rsh/arp-scan/arp-scan...done.
(gdb) b get_source_ip
Breakpoint 1 at 0x804fb65: file arp-scan.c, line 2420.
(gdb) run -I eth0:0 --localnet
Starting program: /home/rsh/arp-scan/arp-scan -I eth0:0 --localnet

Breakpoint 1, get_source_ip (interface_name=0x8059008 "eth0:0",
    ip_addr=0x805747c) at arp-scan.c:2420
2420    get_source_ip(const char *interface_name, uint32_t *ip_addr) {
(gdb) n
2426       struct sockaddr_in *sin = NULL;
(gdb)
2428       if ((pcap_findalldevs(&alldevsp, errbuf)) != 0) {
(gdb)
2432       device=alldevsp;
(gdb) set $temp=alldevsp
(gdb) while ($temp)
 >print $temp->name
 >set $temp = $temp->next
 >end
$1 = 0x80590c8 "eth0"
$2 = 0x80595b8 "nflog"
$3 = 0x80590b8 "any"
$4 = 0x80592d0 "lo"
(gdb) c
Continuing.
ERROR: Could not find interface: eth0:0
ERROR: Check that the interface exists and is up
[Inferior 1 (process 3523) exited with code 01]
(gdb) quit

**Comment by royhills** [comment] 2015-02-20 13:31
Given that the list from pcap_findalldevs() is not exhaustive, we shouldn't exit with an error just because we can't find the name in the list. So the OP is correct that the old "continue with warning" behaviour was better.

**Comment by Silex** [comment] 2015-02-20 13:48
Good news. Should I expect some rollback to the old behavior soonish?

**Comment by Silex** [comment] 2015-03-10 13:27
@royhills: are you the maintainer of arp-scan? if no, where can I send some emails/bugreports?

**Comment by royhills** [comment] 2015-03-10 13:40
Yes, I'm the maintainer. But only in my spare time; it's not a full-time project for me.

Bug reports can go on github, and guggested fixed can be made via a pull request.

Roy

Date: Tue, 10 Mar 2015 06:27:59 -0700

**Comment by Silex** [comment] 2015-03-10 13:59
Ah, ok then I'll just wait on this issue and use `-s` in the meantime :)

Thanks.

**Comment by royhills** [comment] 2021-11-17 12:37
The behaviour of get_source_ip() was changed in e360d46471b1053e4f936bea03958c004ee4a223 so that it tries to use getifaddrs() if that function is available and pcap_findalldevs() fails to find the device address.

This has only been tested on Linux so far, but it appears to work and allows the use of Linux alias interfaces such as ens33:0.

If this fix works then it should solve this issue, but more work needs to be done to check portability and ensure no regressions.

**Comment by royhills** [comment] 2021-11-29 15:19
No obvious regressions against https://github.com/royhills/arp-scan/commit/1749e3a09bb1218750f582e7094ed3cf7cd83097

Closing this issue.  Please re-open if the problem persists.

**Closed by royhills** 2021-11-29 15:19 UTC
